# print("João Pedro")
# print("Olá, mundo")
nome = input("Digite seu nome: ")
dia = input("Digite o dia que você nasceu: ")
mes = input("digite o mes que você nasceu: ")
ano = input("digite o ano que você nasceu: ")
print(f"Seu nome é {nome} e você nasceu no dia {dia} do {mes} de {ano}")
